### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ru4ert**
Typo

### CODE REVIEW

**Comment by ru4ert** [comment]
fix for #44

**Comment by yhirose** [comment]
@ why did you add 'Add other properties' section again?

**Comment by ru4ert** [comment]
@yhirose because these steps are required too, if you follow your steps.

**Comment by yhirose** [comment]
@Rupert-com, in other words, there already exists the same exact thing right under the 'Adjust package.json' in README. Why is the same thing needed again? Or am I missing something to understand what you are trying to do with it?

image

**Comment by ru4ert** [comment]
@yhirose oh, okay. Nope, now I was wrong with the second commit. You're right, i missed these two.

**Pull request merged**
